export default {
    serviceInfo() {
        return [
            {
                label: 'ml-va',
                title: 'Cloud AutoML Vision BETA',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">是一套機器學習產品，即使開發人員的機器學習專業知識有限，也能利用</span> Google <span style="font-family:&quot;新細明體&quot;,serif">先進的遷移學習與神經架構搜尋技術，訓練出符合自身業務需求的高品質模型，</span>Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">透過</span> Google <span style="font-family:&quot;新細明體&quot;,serif">享有專利的技術，提供絕佳效能和準確的預測功能，讓使用者能夠充分運用開發至今超過</span> 10 <span style="font-family:&quot;新細明體&quot;,serif">年的</span> Google Research <span style="font-family:&quot;新細明體&quot;,serif">技術。</span>Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">提供簡單明瞭的圖形化使用者介面</span> (GUI)<span style="font-family:&quot;新細明體&quot;,serif">，方便您根據自己的資料訓練、評估、改善及部署模型。您只需要幾分鐘的時間，就能建立專屬於您的自訂機器學習模型。您可以使用</span> Google <span style="font-family:&quot;新細明體&quot;,serif">的人工標籤服務，由真人為標籤加註或清理標籤，藉此確保訓練模型時使用的是品質絕佳的資料，目前</span>AutoML<span style="font-family:&quot;新細明體&quot;,serif">共提供有</span>Vision<span style="font-family:&quot;新細明體&quot;,serif">、</span>Natural Language<span style="font-family:&quot;新細明體&quot;,serif">與</span>Translation<span style="font-family:&quot;新細明體&quot;,serif">三個</span>BETA<span style="font-family:&quot;新細明體&quot;,serif">的版本。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/automl/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/automl/</a></u></span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p>`,
                route: 'vision-api',
                redirectBtn: '開始辨識'
            },{
                label: 'ml-nla',
                title: 'Cloud AutoML Natural Language BETA',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">是一套機器學習產品，即使開發人員的機器學習專業知識有限，也能利用</span> Google <span style="font-family:&quot;新細明體&quot;,serif">先進的遷移學習與神經架構搜尋技術，訓練出符合自身業務需求的高品質模型，</span>Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">透過</span> Google <span style="font-family:&quot;新細明體&quot;,serif">享有專利的技術，提供絕佳效能和準確的預測功能，讓使用者能夠充分運用開發至今超過</span> 10 <span style="font-family:&quot;新細明體&quot;,serif">年的</span> Google Research <span style="font-family:&quot;新細明體&quot;,serif">技術。</span>Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">提供簡單明瞭的圖形化使用者介面</span> (GUI)<span style="font-family:&quot;新細明體&quot;,serif">，方便您根據自己的資料訓練、評估、改善及部署模型。您只需要幾分鐘的時間，就能建立專屬於您的自訂機器學習模型。您可以使用</span> Google <span style="font-family:&quot;新細明體&quot;,serif">的人工標籤服務，由真人為標籤加註或清理標籤，藉此確保訓練模型時使用的是品質絕佳的資料，目前</span>AutoML<span style="font-family:&quot;新細明體&quot;,serif">共提供有</span>Vision<span style="font-family:&quot;新細明體&quot;,serif">、</span>Natural Language<span style="font-family:&quot;新細明體&quot;,serif">與</span>Translation<span style="font-family:&quot;新細明體&quot;,serif">三個</span>BETA<span style="font-family:&quot;新細明體&quot;,serif">的版本。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/automl/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/automl/</a></u></span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'ml-ta',
                title: 'Cloud AutoML Translation BETA',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">是一套機器學習產品，即使開發人員的機器學習專業知識有限，也能利用</span> Google <span style="font-family:&quot;新細明體&quot;,serif">先進的遷移學習與神經架構搜尋技術，訓練出符合自身業務需求的高品質模型，</span>Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">透過</span> Google <span style="font-family:&quot;新細明體&quot;,serif">享有專利的技術，提供絕佳效能和準確的預測功能，讓使用者能夠充分運用開發至今超過</span> 10 <span style="font-family:&quot;新細明體&quot;,serif">年的</span> Google Research <span style="font-family:&quot;新細明體&quot;,serif">技術。</span>Cloud AutoML <span style="font-family:&quot;新細明體&quot;,serif">提供簡單明瞭的圖形化使用者介面</span> (GUI)<span style="font-family:&quot;新細明體&quot;,serif">，方便您根據自己的資料訓練、評估、改善及部署模型。您只需要幾分鐘的時間，就能建立專屬於您的自訂機器學習模型。您可以使用</span> Google <span style="font-family:&quot;新細明體&quot;,serif">的人工標籤服務，由真人為標籤加註或清理標籤，藉此確保訓練模型時使用的是品質絕佳的資料，目前</span>AutoML<span style="font-family:&quot;新細明體&quot;,serif">共提供有</span>Vision<span style="font-family:&quot;新細明體&quot;,serif">、</span>Natural Language<span style="font-family:&quot;新細明體&quot;,serif">與</span>Translation<span style="font-family:&quot;新細明體&quot;,serif">三個</span>BETA<span style="font-family:&quot;新細明體&quot;,serif">的版本。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/automl/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/automl/</a></u></span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'vi',
                title: 'Cloud Video Intelligence',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Google Cloud Video <span style="font-family:&quot;新細明體&quot;,serif">可以透過簡單易用的</span> REST API <span style="font-family:&quot;新細明體&quot;,serif">擷取影片中繼資料，讓觀眾更容易找到您的影片、提升影片的曝光率。此外，您現在還能搜尋目錄中所有影片檔案的任何時間點。這項服務可以為</span> Google Cloud Storage <span style="font-family:&quot;新細明體&quot;,serif">中存放的影片快速加上註解，協助您識別影片中的重要實體</span> (<span style="font-family:&quot;新細明體&quot;,serif">名詞</span>)<span style="font-family:&quot;新細明體&quot;,serif">，以及這類實體在影片中出現的時間點。您還能從整部影片、各個鏡頭或單一影格中擷取相關資訊，將實際的訊號內容與雜訊分開。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/video-intelligence/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/video-intelligence/</a></u></span></span></span></p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'ta',
                title: 'Cloud Translation',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Cloud Translation <span style="font-family:&quot;新細明體&quot;,serif">包含備有預先訓練模型的</span> API<span style="font-family:&quot;新細明體&quot;,serif">，以及可依個人需求建構模型的</span> AutoML Translation<span style="font-family:&quot;新細明體&quot;,serif">。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Translation API <span style="font-family:&quot;新細明體&quot;,serif">提供簡單的程式介面，可使用最先進的神經機器翻譯技術，將任意字串翻譯成任何支援的語言。其具備快速回應能力，因此網站和應用程式可以整合</span> Translation API<span style="font-family:&quot;新細明體&quot;,serif">，以提供快速的動態翻譯功能，將原文從原文語言翻譯成譯文語言</span> (<span style="font-family:&quot;新細明體&quot;,serif">例如將法文翻譯成英文</span>)<span style="font-family:&quot;新細明體&quot;,serif">。當原文語言不明時，此</span> API <span style="font-family:&quot;新細明體&quot;,serif">也具備語言偵測功能，可自動辨識。這項基礎技術會時常更新，持續納入</span> Google <span style="font-family:&quot;新細明體&quot;,serif">研究小組改善之處，提供更好的翻譯結果以及新的語言和語言組合。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/translate/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/translate/</a></u></span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'sa',
                title: 'Cloud Speech',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">有了</span> Google Cloud Speech-to-Text <span style="font-family:&quot;新細明體&quot;,serif">這個容易使用的</span> API<span style="font-family:&quot;新細明體&quot;,serif">，開發人員就能透過其中的強大神經網路模型，將音訊轉換成文字。這個</span> API <span style="font-family:&quot;新細明體&quot;,serif">能辨識超過</span> 120 <span style="font-family:&quot;新細明體&quot;,serif">種語言和方言，滿足全球各地使用者的需求，讓您啟用語音指令和控制功能、將客服中心的語音音訊轉錄為文字，以及用於其他用途。此外，借助</span> Google <span style="font-family:&quot;新細明體&quot;,serif">的機器學習技術，這個</span> API <span style="font-family:&quot;新細明體&quot;,serif">也能處理即時串流播放，或預先錄製的音訊。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/speech-to-text/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/speech-to-text/</a></u></span></span></span></p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'dee',
                title: 'Dialogflow Enterprise Edition',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">通過構建引人入勝的語音和基於文本的會話界面（例如由</span>AI<span style="font-family:&quot;新細明體&quot;,serif">提供支持的語音應用和聊天機器人），為用戶提供與產品交互的新方式。與您網站，移動應用，</span>Google<span style="font-family:&quot;新細明體&quot;,serif">智能助理，亞馬遜</span>Alexa<span style="font-family:&quot;新細明體&quot;,serif">，</span>Facebook Messenger<span style="font-family:&quot;新細明體&quot;,serif">以及其他常用平台和設備上的用戶建立聯繫。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><div class="video-embbed-container"><iframe frameborder="0" height="315" src="https://www.youtube.com/embed/yT58gTXdQb8" width="560"></iframe></div><p>&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://dialogflow.com/" style="color:#0563c1; text-decoration:underline">https://dialogflow.com/</a></u></span></span></span></p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'va',
                title: 'Cloud Vision',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Cloud Vision <span style="font-family:&quot;新細明體&quot;,serif">可透過</span> API <span style="font-family:&quot;新細明體&quot;,serif">提供經過預先訓練的模型，且能使用</span> AutoML Vision <span style="font-family:&quot;新細明體&quot;,serif">建構自訂模型，可根據您的使用案例調整彈性。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Cloud Vision API <span style="font-family:&quot;新細明體&quot;,serif">讓開發人員在容易使用的</span> REST API <span style="font-family:&quot;新細明體&quot;,serif">中，透過封裝強大的機器學習模型瞭解圖片內容。它可以快速將圖片歸類至數千種類別之一</span> (<span style="font-family:&quot;新細明體&quot;,serif">例如「帆船」</span>)<span style="font-family:&quot;新細明體&quot;,serif">、偵測圖片內的個別物件和臉部，且可讀取圖片中的印刷文字。您可以透過圖片情緒分析，在圖片目錄中建構中繼資料、審核令人反感的內容，或加入新的行銷方案。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/vision/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/vision/</a></u></span></span></span></p>`,
                route: null,
                redirectBtn: '開發中'
            },{
                label: 'nla',
                title: 'Cloud Natural Language',
                content: `<p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif">Google Cloud Natural Language <span style="font-family:&quot;新細明體&quot;,serif">可藉由便於使用的</span> REST API <span style="font-family:&quot;新細明體&quot;,serif">提供預先訓練的強大機器學習模型，並以</span> AutoML Natural Language<span style="font-family:&quot;新細明體&quot;,serif">測試版輕鬆建構自訂模型，進而解析文字的結構與意義。進一步瞭解</span> Cloud AutoML<span style="font-family:&quot;新細明體&quot;,serif">。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">您可以使用</span> Cloud Natural Language <span style="font-family:&quot;新細明體&quot;,serif">來擷取文字文件、新聞或網誌文章中的人事時地物等相關資訊，並瞭解您的產品在社交媒體上引起的情緒迴響，或是剖析客服中心或簡訊應用程式中的客戶對話背後意圖。您可以分析在要求中上傳的文字，或整合您在</span> Google Cloud Storage <span style="font-family:&quot;新細明體&quot;,serif">上的文件儲存空間。</span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p><p style="margin-left:0cm; margin-right:0cm"><span style="font-size:12pt"><span style="font-family:Calibri,sans-serif"><span style="font-family:&quot;新細明體&quot;,serif">參考連結：</span><span style="color:#0563c1"><u><a href="https://cloud.google.com/natural-language/" style="color:#0563c1; text-decoration:underline">https://cloud.google.com/natural-language/</a></u></span></span></span></p><p style="margin-left:0cm; margin-right:0cm">&nbsp;</p>`,
                route: null,
                redirectBtn: '開發中'
            }
        ]
    }
}